version: '3'
services:
#  bot:
#    build:
#      context: .
#    networks:
#      - schedule

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: schedule
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - schedule

networks:
  schedule:
    driver: bridge
