"""Add day for lesson

Revision ID: dc817d01c714
Revises: a3f0bbb40c44
Create Date: 2024-10-05 15:54:54.399867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc817d01c714'
down_revision: Union[str, None] = 'a3f0bbb40c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_days_id'), 'days', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.add_column('lessons', sa.Column('day_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lessons', 'days', ['day_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'day_id')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_days_id'), table_name='days')
    op.drop_table('days')
    # ### end Alembic commands ###
